import ContentLoader from "react-content-loader";

const Loader = ({ type = "", count = 1 }) => {
	return (
		<div className="space-y-8">
			{Array.from({ length: count }).map((value, index) => {
				if (type === "assignmentCard")
					return (
						<ContentLoader
							key={index}
							speed={1.25}
							width={1000}
							height={150}
							backgroundColor="#f1f1f1"
							foregroundColor="#ececec"
						>
							<rect
								x="0"
								y="0"
								rx="16"
								ry="16"
								width="300"
								height="150"
							/>
							<rect
								x="340"
								y="10"
								rx="4"
								ry="4"
								width="400"
								height="20"
							/>
							<rect
								x="340"
								y="45"
								rx="4"
								ry="4"
								width="50"
								height="24"
							/>
							<rect
								x="400"
								y="45"
								rx="4"
								ry="4"
								width="120"
								height="24"
							/>
							<rect
								x="340"
								y="80"
								rx="4"
								ry="4"
								width="650"
								height="12"
							/>
							<rect
								x="600"
								y="110"
								rx="6"
								ry="6"
								width="100"
								height="24"
							/>
						</ContentLoader>
					);
				else if (type === "mySubmissionCard")
					return (
						<ContentLoader
							key={index}
							speed={1.25}
							width={700}
							height={220}
							backgroundColor="#f1f1f1"
							foregroundColor="#ececec"
						>
							<rect
								x="10"
								y="10"
								rx="4"
								ry="4"
								width="450"
								height="20"
							/>
							<rect
								x="10"
								y="45"
								rx="4"
								ry="4"
								width="350"
								height="18"
							/>
							<rect
								x="10"
								y="80"
								rx="4"
								ry="4"
								width="150"
								height="16"
							/>
							<rect
								x="10"
								y="105"
								rx="4"
								ry="4"
								width="150"
								height="16"
							/>
							<rect
								x="10"
								y="130"
								rx="4"
								ry="4"
								width="150"
								height="16"
							/>
							<rect
								x="10"
								y="165"
								rx="8"
								ry="8"
								width="650"
								height="48"
							/>
						</ContentLoader>
					);
			})}
		</div>
	);
};

export default Loader;
